version: '3.8'
services:
  postgres:
    image: postgres:15.3-alpine
    ports:
      - '5433:5432'
    networks:
      - backend
    environment:
      - POSTGRES_USER=flameaxe
      - POSTGRES_PASSWORD=123456
    volumes:
      - dbdata:/var/lib/postgresql/data

  rails:
    build: .
    ports:
      - '25565:3000'
    depends_on:
      - postgres
    networks:
      - backend
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - POSTGRES_URL=postgres://flameaxe:123456@postgres:5432
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./tmp/vods:/app/public/vods

  redis:
    image: redis:6.2.5
    ports:
      - '6380:6379'
    networks:
      - backend

  open_media_engine:
    build:
      context: .
      dockerfile: oem.Dockerfile
    ports:
      - '1935:1935'
      - '9999:9999/udp'
      - '9000:9000'
      - '3333:3333'
      - '3334:3334'
      - '3478:3478'
      - '10000-10009:10000-10009/udp'

volumes:
  dbdata:

networks:
  backend:
    driver: bridge
