
version: '3.8'
services:
  postgres:
    image: postgres:15.3-alpine
    ports:
      - '5433:5432'
    networks:
        - backend
    environment:
        - POSTGRES_USER=flameaxe
        - POSTGRES_PASSWORD=123456
    volumes:
      - dbdata:/var/lib/postgresql/data

  rails:
    build: .
    ports:
      - '3001:3001'
    depends_on:
        - postgres
    networks:
        - backend
    environment:
      - REDIS_URL=redis://redis:6380/0
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - POSTGRES_URL=postgres://flameaxe:123456@postgres:5432
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./tmp/vods:/app/public/vods

  redis:
    image: redis:6.2.5
    ports:
      - '6380:6379'
    networks:
        - backend

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
        - '80:80'
        - '443:443'
        - '1935:1935'
    depends_on:
        - rails
    networks:
        - backend
    volumes:
      - ./tmp/vods:/tmp/vods

volumes:
  dbdata:

networks:
    backend:
      driver: bridge