default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['POSTGRES_URL'] %>

development:
  <<: *default
  database: rtmp_development

test:
  <<: *default
  database: rtmp_test

production:
  <<: *default
  database: rtmp_production
